services:
  bobbi-watchdog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bobbi-watchdog
    cap_add:
      - NET_ADMIN  # Required for packet capture
    restart: unless-stopped
    volumes:
      - ./captured_files:/app/captured_files
      - ./clamd.conf:/etc/clamav/clamd.conf:ro # Mount clamd.conf
    environment:
      - INTERFACE=eth0  # Default to macOS primary interface, change as needed
      - THREAT_THRESHOLD=50 # Example, can be overridden
    network_mode: host  # Use host network mode for direct access to host network interfaces
