services:
  bobbi-watchdog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bobbi-watchdog
    cap_add:
      - NET_ADMIN  # Required for packet capture
    restart: unless-stopped
    volumes:
      - ./captured_files:/app/captured_files
      - ./clamd.conf:/etc/clamav/clamd.conf:ro # Mount clamd.conf
    environment:
      - INTERFACE=eth0  # Default interface, might need adjustment for Ubuntu
      - THREAT_THRESHOLD=50 # Example, can be overridden
    networks:
      bobbi_net:
        ipv4_address: 172.20.0.2

# Define the custom network
networks:
  bobbi_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
